### ISSUE TITLE
My debug app gets freezes on splash image when I run it from my mobile.

### ISSUE THREAD

**Issue by eivanphils** [bakerframework/baker-android-refactor#1]
My baker app loads on my android simulator, I can see the newstand after 2min watching the splash image.

On the other hand, once I generate a signed app in debug or release mode, it doesn't load on my smartphone. 

What can I do? Any idea for this issue? I'm desperate.
Thanks a lot, and thanks for Baker.

**Comment by eezau** [comment]
I have same problem.
I connected android-tablet to computer and I got error messages below.
25465-25491/application.name E/NativeCrypto: ssl=0x50d1d058 cert_verify_callback x509_store_ctx=052dbcad8 arg=0x0

25465-25491/application.name E/NativeCrypto: ssl=0x50d1d058 cert_verify_callback calling verifyCertificateChain authMethod=RSA

Android version 4.1.2

**Comment by fcontreras** [comment]
Greeting Guys

This is yet not a stable version of the Baker code... please refer to the main one.

**Comment by tobiasstrebitzer** [comment]
Hi @eivanphils  and @eezau. We have just released a new version of android-baker-refactor (v4.3.0) that will most likely solve the issues you're having. Have a look at the [Installation Guide](https://github.com/bakerframework/baker-android-refactor/wiki/Tutorial---Installation-Guide).

Please re-open this issue if you still have any problems launching the app.
