### ISSUE TITLE
Issue reading problem

### ISSUE THREAD

**Issue by uncledent** [bakerframework/baker-android-refactor#10]
Hello, I'm testing the Baker Android App and have a problem. When I open my hpub I see a blank white screen, when I double tap the screen my index appears (as normally) and I can click a page in an index, but it is being opened in a modal window.

What could be the reason? iOS works perfectly. It is the same pub with an index file. Does android version have known issues with it? 

How do I add google play to the cloud console? 

Thank you in advance!

P.S. Sorry for screenshots, I'm not a great android user and have a very bad device :) iPhone rules :)
![img_1424](https://cloud.githubusercontent.com/assets/6542981/7252804/582143e6-e838-11e4-8f32-ebe3e8f7fa9d.JPG)
![img_1426](https://cloud.githubusercontent.com/assets/6542981/7252806/5891f08c-e838-11e4-90c8-1a811764919f.JPG)

**Comment by uncledent** [comment]
One more comment. Could this be because I store pages inside of a directory and not in root? Example from book.json:
{"title":"Обложка" ,"url":"pages/cover.html"},

**Comment by uncledent** [comment]
Just tested it with the pages in the root, it didn't  help

**Comment by uncledent** [comment]
Here is the log, when I open Issue:

04-23 05:38:27.374    2174-2328/com.magloft.demo I/ParseBookJsonJob﹕ start
04-23 05:38:27.374    2174-2174/com.magloft.demo W/GAV4﹕ Thread[main,5,main]: Missing tracking id (&tid) parameter.
04-23 05:38:27.382    2174-2328/com.magloft.demo I/ParseBookJsonJob﹕ completed
04-23 05:38:27.678    2174-2174/com.magloft.demo D/class com.bakerframework.baker.activity.IssueActivity﹕ THE RAW BOOK.JSON IS: {"orientation":"PORTRAIT","contents":["{\"title\":\"Обложка\",\"url\":\"pages\\/cover.html\"}","{\"title\":\"Как пользоваться приложением\",\"url\":\"pages\\/instructions.html\"}","{\"title\":\"От редактора\",\"url\":\"pages\\/ot_redaktora.html\"}","{\"title\":\"Вопросы в редакцию\",\"url\":\"pages\\/pisma.html\"}","{\"title\":\"Инфограф\",\"url\":\"pages\\/infograf.html\"}","{\"title\":\"JORNLист\",\"url\":\"pages\\/jornlist.html\"}","{\"title\":\"Синема\",\"url\":\"pages\\/kino.html\"}","{\"title\":\"Фактосфера\",\"url\":\"pages\\/faktosfera.html\"}","{\"title\":\"Будапешт\",\"url\":\"pages\\/polet.html\"}","{\"title\":\"По Европе  на велосипеде\",\"url\":\"pages\\/velo.html\"}","{\"title\":\"Лайфхак от Маяковского. Как выглядеть крутым перцем, когда ты безнадежный лирик\",\"url\":\"pages\\/mayakovskij.html\"}","{\"title\":\"Взрослы�� игры с мячом\",\"url\":\"pages\\/bumperball.html\"}","{\"title\":\"Eating outside: за и против\",\"url\":\"pages\\/eat_outside.html\"}","{\"title\":\"Делай и богатей\",\"url\":\"pages\\/dengi.html\"}","{\"title\":\"Дистанционный смотритель\",\"url\":\"pages\\/seriali.html\"}","{\"title\":\"Любовь втроем\",\"url\":\"pages\\/lubov_vztroem.html\"}","{\"title\":\"Ключ к ее оргазму\",\"url\":\"pages\\/orgazm.html\"}","{\"title\":\"Фитнес-новости\",\"url\":\"pages\\/fitness.html\"}","{\"title\":\"Юрий Обрывченко\",\"url\":\"pages\\/obryvchenko.html\"}","{\"title\":\"Как худому набрать вес\",\"url\":\"pages\\/ves.html\"}","{\"title\":\"Присед\",\"url\":\"pages\\/prised.html\"}","{\"title\":\"Береги себя. Как избежать травм\",\"url\":\"pages\\/travmi.html\"}","{\"title\":\"Такая разная курица\",\"url\":\"pages\\/fsk.html\"}","{\"title\":\"Робин Уильямс: Эйнштейн комедии\",\"url\":\"pages\\/robin.html\"}","{\"title\":\"Твой стержень\",\"url\":\"pages\\/sterjen.html\"}","{\"title\":\"12 секретов успеха от создателя Facebook Марка Цукерберга\",\"url\":\"pages\\/zuckerberg.html\"}","{\"title\":\"Умный дом\",\"url\":\"pages\\/dom.html\"}","{\"title\":\"Альтернативный транспорт\",\"url\":\"pages\\/alternativnij_transport.html\"}","{\"title\":\"Спутники героев\",\"url\":\"pages\\/gopro.html\"}","{\"title\":\"День умного дурака\",\"url\":\"pages\\/shnobel.html\"}","{\"title\":\"Теория эволюции – уже не теория\",\"url\":\"pages\\/evolution.html\"}","{\"title\":\"Мини-гид по ГОА\",\"url\":\"pages\\/goa.html\"}","{\"title\":\"Правильная борода\",\"url\":\"pages\\/boroda.html\"}","{\"title\":\"Мы в социальных сетях\",\"url\":\"pages\\/social.html\"}","{\"title\":\"Над номером работали\",\"url\":\"pages\\/nad_nomerom.html\"}"],"-baker-index-height":0,"zoomable":false,"hpub":"1","-baker-vertical-bounce":false,"date":"2015-04-23","url":"pages\/book:\/\/jornl.ru","creator":[],"-baker-page-numbers-color":"","author":[],"-baker-background":"","-baker-media-autoplay":false,"cover":"","title":"Апрель 2015","-baker-page-turn-tap":false,"-baker-rendering":""}
04-23 05:38:27.682    2174-2174/com.magloft.demo D/class com.bakerframework.baker.activity.IssueActivity﹕ THE PATH FOR LOADING THE PAGES WILL BE: file:///storage/emulated/0/Android/data/com.magloft.demo/files/issues/
04-23 05:38:27.686    2174-2174/com.magloft.demo W/GAV4﹕ Thread[main,5,main]: Missing tracking id (&tid) parameter.
04-23 05:38:27.758    2174-2174/com.magloft.demo W/EGL_genymotion﹕ eglSurfaceAttrib not implemented
04-23 05:38:27.926    2174-2279/com.magloft.demo E/EGL_genymotion﹕ eglQuerySurface 30be  EGL_BAD_ATTRIBUTE
04-23 05:38:28.022    2174-2279/com.magloft.demo E/chromium﹕ [ERROR:buffer_manager.cc(313)] [.BrowserCompositor-0xb9545ba8]GL ERROR :GL_INVALID_OPERATION : glBufferData: <- error from previous GL command
04-23 05:38:28.078    2174-2279/com.magloft.demo E/EGL_genymotion﹕ eglQuerySurface 30be  EGL_BAD_ATTRIBUTE
04-23 05:38:28.154    2174-2174/com.magloft.demo W/BindingManager﹕ Cannot call determinedVisibility() - never saw a connection for the pid: 2174
04-23 05:38:28.162    2174-2279/com.magloft.demo E/chromium﹕ [ERROR:buffer_manager.cc(313)] [.BrowserCompositor-0xb9a170a8]GL ERROR :GL_INVALID_OPERATION : glBufferData: <- error from previous GL command
04-23 05:38:28.170    2174-2174/com.magloft.demo W/BindingManager﹕ Cannot call determinedVisibility() - never saw a connection for the pid: 2174
04-23 05:38:28.186    2174-2174/com.magloft.demo I/chromium﹕ [INFO:CONSOLE(7)] "The value "202;initial-scale" for key "height" was truncated to its numeric prefix.", source: file:///storage/emulated/0/Android/data/com.magloft.demo/files/issues/04_2015/index.html (7)
04-23 05:38:28.186    2174-2174/com.magloft.demo I/chromium﹕ [INFO:CONSOLE(7)] "The key "1" is not recognized and ignored.", source: file:///storage/emulated/0/Android/data/com.magloft.demo/files/issues/04_2015/index.html (7)
04-23 05:38:28.186    2174-2174/com.magloft.demo I/chromium﹕ [INFO:CONSOLE(7)] "Error parsing a meta element's content: ';' is not a valid key-value pair separator. Please use ',' instead.", source: file:///storage/emulated/0/Android/data/com.magloft.demo/files/issues/04_2015/index.html (7)
04-23 05:41:32.154    2174-2341/com.magloft.demo W/DefaultRequestDirector﹕ Authentication error: Unable to respond to any of these challenges: {}

**Comment by uncledent** [comment]
Solved it. Just removed "title" from content part of the json and edited link part of the code to ignore my /pages/ part of the string.

**Comment by Fireoverload** [comment]
Hi uncledent, 

I got the same problem. Could you please tell me how you edited the link part of the code to get this to work?

Thanks alot!
