### ISSUE TITLE
Easier way to test?

### ISSUE THREAD

**Issue by codegeek511** [bakerframework/baker-android-refactor#11]
To rest my app on the emulator I have to export it as an .apk then install it to the virtual device in terminal. Is their an easier way to do this? It doesn't take that long, but for making minor fixes and checking them is taxing.

**Comment by fcontreras** [comment]
If you are using Android Studio you should be able to hit the debug button (which I think is a green bug if Im not wrong) and that should prompt you to select one of your active devices (virtual or not).

**Comment by codegeek511** [comment]
@fcontreras You are right, I tried that at first but it just took a really long time to run it. Thanks

**Comment by uncledent** [comment]
@codegeek511 Had the same problem, just found a better way https://www.genymotion.com like 15 minutes ago, it is free and fast. U can use it with Android Studio as well.

**Comment by codegeek511** [comment]
@uncledent Just got it running......Genymotion is awesome! Thanks dude.

**Comment by uncledent** [comment]
@codegeek511 u're welcome. Android is a madness))) Wish baker was as good on android as on iOS)

**Comment by codegeek511** [comment]
@uncledent glad to know its not just me :) Also any reason why when running my app it just sits at the loading screen. I was using it then I ran it again and it is just loading.....no errors or anything.

**Comment by codegeek511** [comment]
Found it, it was a bad json......not even sure what was wrong with it

**Comment by mpavlidis** [comment]
@codegeek511 how did you fix the bad json ?? because i have the same problem and cant find how to fix it
