### ISSUE TITLE
Can't find where to change this color.

### ISSUE THREAD

**Issue by codegeek511** [bakerframework/baker-android-refactor#12]
I have looked all around the res folder, but cannot seem to find the color for the Date text.
![screen shot 2015-04-23 at 5 25 54 pm](https://cloud.githubusercontent.com/assets/5607372/7310259/f93cd686-e9dd-11e4-89a8-10f8e8a97269.png)
I need to change the text that is red.

**Comment by uncledent** [comment]
hi @codegeek511, you can change this colors in res->layout->issue_card_view.xml, just click on this text and change the color in the properties panel.

**Comment by codegeek511** [comment]
@uncledent sweet thanks. Also there is a red x to x out of the info page, where is that located?
