### ISSUE TITLE
Slow page loading

### ISSUE THREAD

**Issue by uncledent** [bakerframework/baker-android-refactor#13]
Hello, when reading magazine the pages load very slow, the web view is being created first for a while, and then it takes much time to render page. A white screen is being shown during this time. Is there any chance to make it load faster? Or is android related? Backer on iOS works much much faster.

Thank you in advance for the answer.

**Comment by fcontreras** [comment]
Hi @uncledent what device are you using for testing?

**Comment by uncledent** [comment]
Hi @fcontreras, I used a couple of devices and it is really slow and the pages are being rendered with errors or not rendered at all.

**Comment by drking0211** [comment]
I have also come across this problem and the log files don't give much of a clue.

This occurs on a  number of devices running kit-kat. 

Any ideas?

Regards

David

**Comment by selini** [comment]
I have the same problem.I have created a page with contents when i pick a page that is 30 pages away for example  it stuck in white screen and takes a lot time to render.I don't know what to do. I have test it in many devices.
