### ISSUE TITLE
In-App purchases for baker android?

### ISSUE THREAD

**Issue by codegeek511** [bakerframework/baker-android-refactor#14]
Is this possible to do yet? What backend do you need? I have an iOS using magrocket, and it would be awesome if my android app could use it too.

**Comment by codegeek511** [comment]
@tobiasstrebitzer What do you guys use for the In-App purchases?

**Comment by codegeek511** [comment]
@fcontreras has anyone been able to see this?

**Comment by fcontreras** [comment]
@codegeek511 we have this as a "next to" plan to verify the integration of Baker AndroidR in-app to the Baker console.. maybe in couple of weeks we can have a more solid answer to your question.

**Comment by eezau** [comment]
We need this feature also. Do you have any updates when this will be see daylight?

**Comment by eezau** [comment]
We really need this. I think that I need to call some friends and ask if them help you and if they can do this. I only need information when this possible is coming, then I know if I still wait or I choose that second option.

**Comment by uncledent** [comment]
We need this stuff too. Maybe you could give us the callback function, so that we implement it by ourselves?

**Comment by omegah3** [comment]
@fcontreras Is there any update on the  In-App purchases ?
It as been over 10 months since you last said you would have a more solid answer, and nothing still.
Can we assume that this project is dead ?

**Comment by fcontreras** [comment]
@omegah3 not much progress... our team is on hold on this project. I wouldn't say is dead but on hold.
