### ISSUE TITLE
Parse Config

### ISSUE THREAD

**Issue by rovissi** [bakerframework/baker-android-refactor#15]
Anyone have a tip to the Parse configuration?
We just config the ID's in strings.xml, need config in other location?

![parse](https://cloud.githubusercontent.com/assets/5166580/7455512/62156b00-f253-11e4-8f03-eb5217f9bc8d.jpg)

**Comment by fcontreras** [comment]
Hi.. 
Your screenshot shows you uncommented the statements in front of the strings for parse.
Should be like this

```
<!--^parse_application_id--><string name="parse_application_id">CODEHERE</string><!--$parse_application_id-->
```

and you have it like this

```
<parse_application_id--><string name="parse_application_id">CODEHERE</string></parse_application_id-->
```

**Comment by rovissi** [comment]
Thanks @fcontreras !
Parse error don´t appear more in my log, but don´t appear in Parse ControlPanel "registered devices".
You have any other tip? We can post my log with other errors

**Comment by rovissi** [comment]
My log, wth my appid changed to com.apptest

05-04 15:12:18.238    1541-1541/com.apptest I/art? Late-enabling -Xcheck:jni
05-04 15:12:19.284    1541-1541/com.apptest W/Zygote? Slow operation: 1068ms so far, now at Zygote.callPostForkChildHooks
05-04 15:12:19.295    1541-1541/com.apptest W/Zygote? Slow operation: 1517 ms in ForkAndSpecializeCommon:PostForkChildHooks returns
05-04 15:12:19.301    1541-1541/com.apptest W/Zygote? Slow operation: 1797ms so far, now at Zygote.nativeForkAndSpecialize
05-04 15:12:21.005    1541-1541/com.apptest W/Zygote? Slow operation: 3505ms so far, now at Zygote.postForkCommon
05-04 15:12:21.005    1541-1541/com.apptest W/Zygote? Slow operation: 3511ms so far, now at zygoteConnection.runOnce: postForkAndSpecialize
05-04 15:12:22.398    1541-1541/com.apptest D/BakerApplication? Initialized 2 plugins
05-04 15:12:22.810    1541-1541/com.apptest D/ParsePlugin? successfully subscribed to the broadcast channel.
05-04 15:12:27.384    1541-1569/com.apptest W/GAV4? Thread[GAThread,5,main]: Service unavailable (code=1), will retry.
05-04 15:12:32.420    1541-1600/com.apptest W/GAV4? Thread[Service Reconnect,5,main]: Service unavailable (code=1), using local store.
05-04 15:16:42.608    2159-2159/com.apptest W/art? Long monitor contention event with owner method=void android.os.Parcel.nativeAppendFrom(long, long, int, int) from Parcel.java:4294967294 waiters=0 for 527ms
05-04 15:16:42.846    2159-2187/com.apptest W/art? Long monitor contention event with owner method=java.io.File com.parse.Parse.getParseDir() from Parse.java:317 waiters=0 for 348ms
05-04 15:16:43.278    2159-2172/com.apptest W/art? Suspending all threads took: 21.443ms
05-04 15:16:43.407    2159-2172/com.apptest I/art? Background sticky concurrent mark sweep GC freed 6130(330KB) AllocSpace objects, 0(0B) LOS objects, 7% free, 2MB/2MB, paused 33.669ms total 267.477ms
05-04 15:16:43.775    2159-2159/com.apptest D/BakerApplication? Initialized 2 plugins
05-04 15:16:44.741    2159-2172/com.apptest I/art? Background partial concurrent mark sweep GC freed 653(56KB) AllocSpace objects, 1(16KB) LOS objects, 39% free, 2MB/4MB, paused 6.318ms total 221.590ms
05-04 15:16:44.866    2159-2159/com.apptest W/GAV4? Thread[main,5,main]: Missing tracking id (&tid) parameter.
05-04 15:16:44.912    2159-2159/com.apptest W/GAV4? Thread[main,5,main]: Missing tracking id (&tid) parameter.
05-04 15:16:44.915    2159-2200/com.apptest D/JOBS? added job id: -2147483647 class: DownloadManifestJob priority: 0 delay: 0 group : application persistent: false requires network: false
05-04 15:16:45.176    2159-2200/com.apptest D/JOBS? pool-1-thread-1: load factor check. true = (0 < 0)|| (0 \* 1 < 1 + 0). consumer thread: false
05-04 15:16:45.176    2159-2200/com.apptest D/JOBS? adding another consumer
05-04 15:16:45.682    2159-2204/com.apptest D/JOBS? starting consumer Thread-182
05-04 15:16:45.720    2159-2204/com.apptest D/JOBS? running job DownloadManifestJob
05-04 15:16:45.873    2159-2204/com.apptest D/DownloadManifestJob? DOWNLOADING FILE: http://www.apptest.com/api/issues/com.apptest/e7d3ddedf7bffced
05-04 15:16:46.412    2159-2205/com.apptest D/OpenGLRenderer? Render dirty regions requested: true
05-04 15:16:46.514    2159-2159/com.apptest D/? HostConnection::get() New Host Connection established 0xabb543a0, tid 2159
05-04 15:16:46.578    2159-2159/com.apptest D/Atlas? Validating map...
05-04 15:16:46.993    2159-2159/com.apptest D/ParsePlugin? successfully subscribed to the broadcast channel.
05-04 15:16:47.296    2159-2205/com.apptest D/libEGL? loaded /system/lib/egl/libEGL_emulation.so
05-04 15:16:47.300    2159-2205/com.apptest D/libEGL? loaded /system/lib/egl/libGLESv1_CM_emulation.so
05-04 15:16:47.316    2159-2205/com.apptest D/libEGL? loaded /system/lib/egl/libGLESv2_emulation.so
05-04 15:16:47.453    2159-2205/com.apptest D/? HostConnection::get() New Host Connection established 0xafa0b780, tid 2205
05-04 15:16:47.484    2159-2204/com.apptest D/JOBS? finished job DownloadManifestJob
05-04 15:16:47.495    2159-2205/com.apptest I/OpenGLRenderer? Initialized EGL, version 1.4
05-04 15:16:47.529    2159-2205/com.apptest D/OpenGLRenderer? Enabling debug mode 0
05-04 15:16:47.555    2159-2205/com.apptest W/EGL_emulation? eglSurfaceAttrib not implemented
05-04 15:16:47.555    2159-2205/com.apptest W/OpenGLRenderer? Failed to set EGL_SWAP_BEHAVIOR on surface 0xafa08f80, error=EGL_SUCCESS
05-04 15:16:47.978    2159-2159/com.apptest D/Checkout? Adding pending request: BillingSupportedRequest(inapp)
05-04 15:16:48.020    2159-2159/com.apptest D/Checkout? Removing pending request: BillingSupportedRequest(inapp)
05-04 15:16:48.023    2159-2159/com.apptest E/Checkout? Error response: 10000 in BillingSupportedRequest(inapp) request
05-04 15:16:48.129    2159-2159/com.apptest D/Checkout? Cancelling request: BillingSupportedRequest(inapp)
05-04 15:16:48.130    2159-2159/com.apptest D/Checkout? Adding pending request: BillingSupportedRequest(subs)
05-04 15:16:48.135    2159-2159/com.apptest D/Checkout? Removing pending request: BillingSupportedRequest(subs)
05-04 15:16:48.138    2159-2159/com.apptest E/Checkout? Error response: 10000 in BillingSupportedRequest(subs) request
05-04 15:16:48.142    2159-2159/com.apptest D/Checkout? Cancelling request: BillingSupportedRequest(subs)
05-04 15:16:48.252    2159-2200/com.apptest D/JOBS? added job id: -2147483646 class: FetchPurchasesJob priority: 0 delay: 0 group : application persistent: false requires network: true
05-04 15:16:48.269    2159-2204/com.apptest D/JOBS? running job FetchPurchasesJob
05-04 15:16:48.269    2159-2204/com.apptest D/FetchPurchasesJob? fetching purchases from http://www.apptest.com/api/issues/com.apptest/api/issues/com.apptest/e7d3ddedf7bffced
05-04 15:16:48.320    2159-2200/com.apptest D/JOBS? pool-1-thread-1: load factor check. false = (1 < 0)|| (1 \* 1 < 0 + 1). consumer thread: false
05-04 15:16:48.391    2159-2159/com.apptest I/Choreographer? Skipped 46 frames!  The application may be doing too much work on its main thread.
05-04 15:16:49.065    2159-2193/com.apptest W/GAV4? Thread[GAThread,5,main]: Service unavailable (code=1), will retry.
05-04 15:16:49.450    2159-2172/com.apptest I/art? Background sticky concurrent mark sweep GC freed 12905(827KB) AllocSpace objects, 3(44KB) LOS objects, 18% free, 3MB/4MB, paused 5.484ms total 88.177ms
05-04 15:16:49.575    2159-2159/com.apptest I/WebViewFactory? Loading com.android.webview version 37 (eng.buildbot-x86) (code 199997)
05-04 15:16:49.614    2159-2159/com.apptest I/LibraryLoader? Loading: webviewchromium
05-04 15:16:49.654    2159-2159/com.apptest I/LibraryLoader? Time to load native libraries: 42 ms (timestamps 4288-4330)
05-04 15:16:49.655    2159-2159/com.apptest I/LibraryLoader? Expected native library version number "",actual native library version number ""
05-04 15:16:49.924    2159-2159/com.apptest V/WebViewChromiumFactoryProvider? Binding Chromium to main looper Looper (main, tid 1) {1df5e284}
05-04 15:16:49.949    2159-2159/com.apptest I/LibraryLoader? Expected native library version number "",actual native library version number ""
05-04 15:16:50.081    2159-2159/com.apptest I/chromium? [INFO:library_loader_hooks.cc(106)] Chromium logging enabled: level = 0, default verbosity = 0
05-04 15:16:50.096    2159-2159/com.apptest I/BrowserStartupController? Initializing chromium process, renderers=0
05-04 15:16:50.149    2159-2159/com.apptest W/art? Attempt to remove local handle scope entry from IRT, ignoring
05-04 15:16:50.352    2159-2159/com.apptest W/chromium? [WARNING:resource_bundle.cc(315)] locale_file_path.empty()
05-04 15:16:50.356    2159-2159/com.apptest I/chromium? [INFO:aw_browser_main_parts.cc(63)] Load from apk succesful, fd=48 off=46092 len=2953
05-04 15:16:50.573    2159-2159/com.apptest I/chromium? [INFO:aw_browser_main_parts.cc(78)] Loading webviewchromium.pak from, fd:49 off:228796 len:643667
05-04 15:16:50.673    2159-2239/com.apptest W/AudioManagerAndroid? Requires BLUETOOTH permission
05-04 15:16:51.064    2159-2159/com.apptest W/chromium? [WARNING:mailbox_synchronizer.cc(36)] MailboxSync not supported due to missing EGL image/fence support
05-04 15:16:52.659    2159-2245/com.apptest W/chromium? [WARNING:proxy_service.cc(901)] PAC support disabled because there is no system implementation
05-04 15:16:52.865    2159-2204/com.apptest D/JOBS? finished job FetchPurchasesJob
05-04 15:16:52.978    2159-2159/com.apptest W/chromium? [WARNING:data_reduction_proxy_settings.cc(403)] SPDY proxy OFF at startup
05-04 15:16:53.325    2159-2172/com.apptest I/art? Background sticky concurrent mark sweep GC freed 3095(248KB) AllocSpace objects, 2(32KB) LOS objects, 7% free, 4MB/4MB, paused 265.592ms total 525.417ms
05-04 15:16:53.355    2159-2159/com.apptest W/art? Attempt to remove local handle scope entry from IRT, ignoring
05-04 15:16:53.368    2159-2159/com.apptest W/AwContents? onDetachedFromWindow called when already detached. Ignoring
05-04 15:16:53.446    2159-2159/com.apptest W/art? Attempt to remove local handle scope entry from IRT, ignoring
05-04 15:16:53.482    2159-2159/com.apptest W/AwContents? onDetachedFromWindow called when already detached. Ignoring
05-04 15:16:54.616    2159-2172/com.apptest W/art? Suspending all threads took: 28.641ms
05-04 15:16:54.700    2159-2229/com.apptest W/GAV4? Thread[Service Reconnect,5,main]: Service unavailable (code=1), using local store.
05-04 15:16:54.861    2159-2172/com.apptest I/art? Background sticky concurrent mark sweep GC freed 194(23KB) AllocSpace objects, 1(16KB) LOS objects, 2% free, 4MB/4MB, paused 101.614ms total 716.023ms
05-04 15:16:55.118    2159-2159/com.apptest D/Checkout? Adding pending request: BillingSupportedRequest(subs)
05-04 15:16:55.135    2159-2159/com.apptest D/Checkout? Removing pending request: BillingSupportedRequest(subs)
05-04 15:16:55.135    2159-2159/com.apptest E/Checkout? Error response: 10000 in BillingSupportedRequest(subs) request
05-04 15:16:55.140    2159-2159/com.apptest D/Checkout? Cancelling request: BillingSupportedRequest(subs)
05-04 15:16:55.141    2159-2159/com.apptest D/Checkout? Adding pending request: BillingSupportedRequest(inapp)
05-04 15:16:55.143    2159-2159/com.apptest D/Checkout? Removing pending request: BillingSupportedRequest(inapp)
05-04 15:16:55.143    2159-2159/com.apptest E/Checkout? Error response: 10000 in BillingSupportedRequest(inapp) request
05-04 15:16:55.143    2159-2159/com.apptest D/Checkout? Cancelling request: BillingSupportedRequest(inapp)
05-04 15:16:55.229    2159-2159/com.apptest W/GAV4? Thread[main,5,main]: Missing tracking id (&tid) parameter.
05-04 15:16:55.324    2159-2159/com.apptest I/Choreographer? Skipped 329 frames!  The application may be doing too much work on its main thread.
05-04 15:16:56.201    2159-2172/com.apptest I/art? Background partial concurrent mark sweep GC freed 2056(135KB) AllocSpace objects, 1(16KB) LOS objects, 39% free, 4MB/7MB, paused 2.198ms total 966.640ms
05-04 15:16:58.405    2159-2159/com.apptest E/libEGL? call to OpenGL ES API with no current context (logged once per thread)
05-04 15:17:00.092    2159-2205/com.apptest W/EGL_emulation? eglSurfaceAttrib not implemented
05-04 15:17:00.092    2159-2205/com.apptest W/OpenGLRenderer? Failed to set EGL_SWAP_BEHAVIOR on surface 0xafa08f80, error=EGL_SUCCESS
05-04 15:17:00.200    2159-2159/com.apptest W/Event? Subscriber to unregister was not registered before: class com.bakerframework.baker.activity.SplashActivity
05-04 15:17:00.330    2159-2159/com.apptest E/com.bakerframework.baker.model.RemoteIssueCollection? Error: 2131558462
05-04 15:17:00.557    2159-2159/com.apptest I/Choreographer? Skipped 230 frames!  The application may be doing too much work on its main thread.
05-04 15:17:01.325    2159-2159/com.apptest I/Choreographer? Skipped 44 frames!  The application may be doing too much work on its main thread.
05-04 15:17:06.870    2159-2159/com.apptest I/Choreographer? Skipped 312 frames!  The application may be doing too much work on its main thread.
05-04 15:17:10.612    2159-2159/com.apptest I/Choreographer? Skipped 80 frames!  The application may be doing too much work on its main thread.
05-04 15:17:11.056    2159-2205/com.apptest E/chromium? [ERROR:buffer_manager.cc(313)] [.Parent-Compositor-0xafa21630]GL ERROR :GL_INVALID_OPERATION : glBufferData: <- error from previous GL command
05-04 15:17:11.203    2159-2159/com.apptest I/Choreographer? Skipped 34 frames!  The application may be doing too much work on its main thread.
05-04 15:17:14.925    2159-2159/com.apptest I/Choreographer? Skipped 67 frames!  The application may be doing too much work on its main thread.
05-04 15:17:16.159    2159-2205/com.apptest E/chromium? [ERROR:buffer_manager.cc(313)] [.Parent-Compositor-0xafa218d0]GL ERROR :GL_INVALID_OPERATION : glBufferData: <- error from previous GL command
05-04 15:17:16.249    2159-2159/com.apptest I/Choreographer? Skipped 69 frames!  The application may be doing too much work on its main thread.
05-04 15:17:19.233    2159-2159/com.apptest I/Choreographer? Skipped 55 frames!  The application may be doing too much work on its main thread.
05-04 15:17:19.938    2159-2159/com.apptest I/Choreographer? Skipped 40 frames!  The application may be doing too much work on its main thread.
05-04 15:17:22.873    2159-2204/com.apptest D/JOBS? Thread-182: load factor check. false = (0 < 0)|| (0 \* 1 < 0 + 0). consumer thread: true
05-04 15:17:22.873    2159-2204/com.apptest D/JOBS? finishing consumer Thread-182

**Comment by codegeek511** [comment]
Same thing happened to me, this was a great help

**Comment by codegeek511** [comment]
But now I get this 
![screen shot 2015-05-05 at 5 13 25 pm](https://cloud.githubusercontent.com/assets/5607372/7485398/15cf24f0-f34a-11e4-9c1c-ef55ac99f31d.png)

**Comment by fcontreras** [comment]
@codegeek511 that means your XML is malformed please check all tags are closed. You can also try an online xml validator if you are not sure.

**Comment by codegeek511** [comment]
@fcontreras  Lol, it was that. But after I fixed those 3 errors then another popped up saying that type "parse_application_id--" is unsupported

**Comment by fcontreras** [comment]
:) you are back at the beginning .. check my first comment on this thread.

**Comment by codegeek511** [comment]
@fcontreras  Hahahaha I copied the wrong one! Oops, my bad. Thanks

**Comment by fcontreras** [comment]
@rovissi if you have more than one app in Parse.. make sure you are setting the right keys
