### ISSUE TITLE
Can't upload an APK for beta testing

### ISSUE THREAD

**Issue by codegeek511** [bakerframework/baker-android-refactor#16]
when I try to upload my release APK I get this message in the Google Play Dev console 
![screen shot 2015-05-07 at 4 09 05 pm](https://cloud.githubusercontent.com/assets/5607372/7527718/670d4b28-f4d3-11e4-98db-78374c2abc4b.png)

I can't find where else to change it in the project, I already changed it the the Strings.xml

**Comment by codegeek511** [comment]
@fcontreras Anybody?

**Comment by codegeek511** [comment]
@fcontreras @tobiasstrebitzer Has anyone been able to see this?

**Comment by fcontreras** [comment]
try the gradle.properties file and update the application-id property with your package name.. rebuild and try to submit again.

**Comment by codegeek511** [comment]
That did it! Thanks, not sure why I wasn't able to find it by the search.
