### ISSUE TITLE
Bug with links

### ISSUE THREAD

**Issue by codegeek511** [bakerframework/baker-android-refactor#18]
When links open in the app there is no way to back to the page.

Also we are embedding fonts, but still the formatting gets messed up and fonts aren't showing up like they do in our iOS version

**Comment by fcontreras** [comment]
Can you post a zip with a page of the issue you are having troubles with... that will help me help you. :)

**Comment by codegeek511** [comment]
@fcontreras Here is the zip https://drive.google.com/file/d/0B5QXMRoG_smsc19xYi1PcURVY00/view?usp=sharing

the font issue is on page 001 and the link issue is on 004
