### ISSUE TITLE
Please, make a wiki on inApps!

### ISSUE THREAD

**Issue by uncledent** [bakerframework/baker-android-refactor#21]
Please make a wiki, we really need it and it is really urgent. Is it planned? Or should we start searching for an own developer to do that? Thank you in advance!

**Comment by rovissi** [comment]
Forget this... don't need only a "wiki", the purchase URL is with a problem.
Do it yourself.

**Comment by uncledent** [comment]
@rovissi what is wrong with the purchase url? Have you already done this? I believe there is no android backend api at all

**Comment by rovissi** [comment]
the backend is ok, but when the app do the sale with google his don't send the purchase URL to the backend, this function is with a problem

**Comment by tobiasstrebitzer** [comment]
I've written a quick documentation of the API Requests to implement android purchases into other Backends:

https://github.com/bakerframework/baker-android-refactor/wiki/Tutorial---Backend-API-Setup
