### ISSUE TITLE
Could not read the shelf from the device

### ISSUE THREAD

**Issue by madrenderman** [bakerframework/baker-android-refactor#22]
Hello guys, 
sorry if this was asked before but I searched on the forum and didn't find a solution.
I'm testing an app created with baker Android on the device (a Samsung Galaxy Note 3 Neo), everything works fine but when I launch the app on the device it returns the error 'Could not read the shelf from the device' and the app close.
Inside Android Studio I changed all the paths in the 'strings.xml' file so I don't know what I'm doing wrong
Anyone can help me ?

This is the path to the json file: http://www.thefridgefoundation.org/rivista/shelf.json

Thank you

Ray

**Comment by mikegapinski** [comment]
That issue also exists on all Android 6.0 devices, with old baker repo and refactor. For me the update simply broke the app. Still looking for a fix tho, it does not seem to be related to storage itself since the shelf.json is being downloaded to cache
