### ISSUE TITLE
White page on webview

### ISSUE THREAD

**Issue by drking0211** [bakerframework/baker-android-refactor#25]
Hello, when I use the index to navigate (double tap) in the baker app, the webview seems to hang on a white page. Has anyone else had this problem and been able to resolve it?

**Comment by Fireoverload** [comment]
Hello, 
i am experiencing the same problem. I can emulate and start the baker app, and download my hpubfile without problems, but after opening it by clicking "READ", the hpub gets loaded, but the only thing i can see is a white screen.  On double tap i can see and use the menu of my hpub, but no actual content is visible.

![bakerwhite](https://cloud.githubusercontent.com/assets/13470558/8854825/3c016010-3162-11e5-93c3-11cc5ce17886.png)

logcat:
07-23 15:28:48.414    2630-2630/xxx.xxx.it W/art﹕ Attempt to remove local handle scope entry from IRT, ignoring
07-23 15:28:48.632    2630-2630/xxx.xxx.it W/ScreenOrientationListener﹕ Removing an inexistent observer!
07-23 15:28:48.635    2630-2630/xxx.xxx.it W/BindingManager﹕ Cannot call determinedVisibility() - never saw a connection for the pid: 2630
07-23 15:28:48.687    2630-3801/xxx.xxx.it E/EGL_emulation﹕ eglQuerySurface 30be  EGL_BAD_ATTRIBUTE
07-23 15:28:48.793    2630-2630/xxx.xxx.it W/BindingManager﹕ Cannot call determinedVisibility() - never saw a connection for the pid: 2630

Thanks for helping!

**Comment by Keopss** [comment]
I have the same problem, please could you help us?

**Comment by electric-car-insider-com** [comment]
I have a similar problem, when our app is opened it works fine. However, sometimes when a user activates an internal hyperlink all new pages are rendered white.

**Comment by codexnovus** [comment]
I had the same problem. We solved by changing the "Title" value in the shelf.json. Originally the title was something like "This Book ENG" and when we changed it to "this_book_eng" started working.

**Comment by selini** [comment]
I have the same problem.When the user open a hyperlink of page inside the book, it stuck on white page.
