### ISSUE TITLE
Problem with video and GIFs

### ISSUE THREAD

**Issue by selini** [bakerframework/baker-android-refactor#28]
I have some issues with the magazine I am creating in android.The problems are videos and GIFs. The videos are html5 and there are on autoplay. They start playing from the previous page and they do not stop after turning to the next page.They stop only after I turn 2 pages.The GIFs just play for one second and then pause.  Any suggestions? Please Help!

**Comment by fcontreras** [comment]
I have seen that video behaviour. Since we keep three pages in memory it will stop only after you turn 2 pages away. There is a simple solution though, add a javascript listener to the window so when it looses the focus it stop the video.

Here is an example using jquery:

``` javascript
//Should pause the videos if the page looses the focus
    window.addEventListener("blur", function() {
        jQuery("video").each(function() {
            var vid = jQuery(this);
            if (!vid[0].paused) {
                vid[0].pause();
            }
        });
    }, true);
```

**Comment by selini** [comment]
ok i will try it. Any suggestions why the  the GIFs are stopping?

**Comment by selini** [comment]
it worked. thanks :)

**Comment by fcontreras** [comment]
Nice, sorry I can't help with the GIF I actually haven't seen that issue, but I let you know if I find something.

**Comment by selini** [comment]
I tried a single  GIF in one page and it worked fine.I guess  the problem is that I have too many GIFs  and that causing them to stop.Thank you again.If I find a solution I will post it.

**Comment by selini** [comment]
I find a solution with the GIFs . I Converted  them into html5 video.It is smaller from GIFs and I play without problem.There are many online tools for it.

**Comment by fcontreras** [comment]
Thats great news .. Thanks for posting.
