### ISSUE TITLE
Can be used?

### ISSUE THREAD

**Issue by kukusumaa** [bakerframework/baker-android-refactor#3]
Is this repository can be used now?
I have an error when try to Make Project
What should i do?
![screen shot 2015-02-26 at 4 06 38 pm](https://cloud.githubusercontent.com/assets/7358198/6388921/95fc9940-bdd1-11e4-89df-483967b73c43.png)

**Comment by fcontreras** [comment]
Hi @QwertyPong, this repo is yet unstable.. we will announce when is ready.
