### ISSUE TITLE
VersionCode and VersionName Question.

### ISSUE THREAD

**Issue by codegeek511** [bakerframework/baker-android-refactor#36]
The Android Manifest file (which is where version updates are made, v.1.1 etc.) seems to be missing the versioncode and versionname parts in your code, and in their place is a apache licensing agreement. Is there any way to change the version number for updates in the baker code?

**Comment by travisday** [comment]
@tobiasstrebitzer Have you had a chance to see this and/or know what is going on?

**Comment by tobiasstrebitzer** [comment]
Hi @codegeek511 @travisday,

the version number can be changed in [app/build.gradle line 13](https://github.com/bakerframework/baker-android-refactor/blob/master/app/build.gradle#L13).
