### ISSUE TITLE
How do I setup the in-app purchase for each issue?

### ISSUE THREAD

**Issue by bobwol** [bakerframework/baker-android-refactor#4]
I'm in doubt with in-app feature.
What do I have to setup:
- BakerCE
- Google Play
- Google Wallet
- shelf.json
- book.json
  ?

It doesn't need to be a wiki, just a few bullets of instruction with comments when strictly needed...

**Comment by tobiasstrebitzer** [comment]
Hi @robsonw, we've just pushed a big update to finally make this project stable. We're creating videos this week on how to set up Google Play and Google Wallet. For shelf.json and book.json, please refer to the BakerCE documentation.

I'll leave this issue open for now until the videos are live.

**Comment by bobwol** [comment]
Hi @tobiasstrebitzer ! Thanks for the comments!
I was looking for more info and I think I'm almost there...

If I'm using the Bakercloud CE:
- need to setup as a Paid issue, and
- need to put the "product_id" for that issue

If I'm using shelf.json:
- need to put the "product_id" directly on the shelf.json

The "product_id" is the same we set up on iTunes Connect, but I still didn't discover how to set up the same "product_id" on Google Play.

Also discover that we need to get the licensing key and put on the source code. 
The book.json stays same as for iOS.

Your videos are a great resource and I think will solve all my doubts.

I'll download the new master and continue the adventure...

Thanks again!

**Comment by brianhummel** [comment]
Hi guys,

I added a managed IAP to Google, added the exact product_id in the shelf.json. Yet, the app doesn't recognize the IAP and just let's me download the edition.
Is there anything else I have to do (I added the Licence key)?

-B

P.S. Really like the refactoring. Nice job!

**Comment by rovissi** [comment]
hi @tobiasstrebitzer,
we have an app made with baker for ios and bakercloud working perfectly, but in this version for android can not hit the inapp.
I see the publications but don't appear the price and the subscription option.
you have any tips?
thanks
