### ISSUE TITLE
Donwload not update progress bar

### ISSUE THREAD

**Issue by mutador** [bakerframework/baker-android-refactor#6]
Hi, if I change de url download on shelf.json in the way like http://www.domain.com/issue.hpub
the progress bar don't update progress.

Any ideas?

**Comment by tobiasstrebitzer** [comment]
Hi mutador,

where are your files hosted? If i remember right, the server needs to be configured to show download progress (i.e. the header needs to send information about the filesize).

Please run the following curl- command, and post the result here:

``` bash
curl -I http://your-server.com/path/to/issue.hpub
```

Here's an example response, with a Content-Length header set:

```
HTTP/1.1 200 OK
Date: Thu, 12 Mar 2015 04:24:26 GMT
Cache-Control: no-cache
Expires: Fri, 11 Mar 2016 04:24:26 GMT
Last-Modified: Sun, 01 Feb 2015 05:34:56 GMT
ETag: "a8141fc53cbb04feb52b3685b060df67"
x-goog-generation: 1422768896759000
x-goog-metageneration: 1
x-goog-stored-content-encoding: identity
x-goog-stored-content-length: 617098
Content-Type: image/jpeg
x-goog-hash: crc32c=II/ooA==
x-goog-hash: md5=qBQfxTy7BP61KzaFsGDfZw==
x-goog-storage-class: STANDARD
Accept-Ranges: bytes
Content-Length: 617098
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: accept
Access-Control-Expose-Headers: origin
Access-Control-Expose-Headers: x-goog-acl
Access-Control-Expose-Headers: content-type
Server: UploadServer ("Built on Feb 27 2015 12:13:16 (1425067996)")
Alternate-Protocol: 80:quic,p=0.08
```

**Comment by mutador** [comment]
hi, the command response

HTTP/1.1 200 OK
Server: nginx/1.6.2
Date: Thu, 19 Mar 2015 12:12:26 GMT
Content-Type: text/plain
Content-Length: 210951512
Connection: keep-alive
Last-Modified: Thu, 19 Mar 2015 11:07:17 GMT
Accept-Ranges: bytes
