### ISSUE TITLE
Webview Did not show the text

### ISSUE THREAD

**Issue by kukusumaa** [bakerframework/baker-android-refactor#8]
Hi, i try to use this repo but when i read the issue, the webview did not show the content.
The error in logcat is : E/webcoreglue﹕ Should not happen: no rect-based-test nodes found.
Like the picture here, 
![device-2015-03-13-161643](https://cloud.githubusercontent.com/assets/7358198/6635799/6e88ef86-c99c-11e4-8197-aeb990ac4fbd.png)
the bottom of text BALI ERM 2014, there is the content text but did not show.
How to fix it?
Thanks

**Comment by tobiasstrebitzer** [comment]
Hi @QwertyPong,

the errors logged by webkit usually don't cause any problems, it's just webkit being very verbose about what's going on when parsing the html.

I can have a closer look if you're willing to share your hpub, or the affected html-file.

Kind Regards,

Tobias

**Comment by kukusumaa** [comment]
Thanks for reply @tobiasstrebitzer,
but when i use the old baker android, it's fine.
This is link for the hpub : http://www.safiahijab.com/magazine/baker.hpub 
And how to setting google billing on this repo?
Thank you.

**Comment by tobiasstrebitzer** [comment]
Hi @QwertyPong,

we have just pushed a new version of the app, integration XWalkView (a chromium-based web view) that might solve the display issues. Please upgrade to the latest version and let me know if it works :-)

I'll write some details on how to connect with google play in the Wiki shortly. I'll let you know when it's updated.

**Comment by uncledent** [comment]
@tobiasstrebitzer Hello Tobias! I haven't found any Google Play Wiki. Is there still no documentation or have I searched not good enough?
